var wordList = [
["ärata", "ae r a tt a"],
["hiljem", "h i l j e m"],
["ja", "j a"],
["ja(2)", "j a a"],
["ja(3)", "e a"],
["kaheksa", "k a h e k s a"],
["kaheksa(2)", "k a e k s a"],
["kaks", "k a k s"],
["kell", "k e l l"],
["kolm", "k o l m"],
["kümme", "k ue m m e"],
["kümmend", "k ue m m e n t"],
["kümmend(2)", "k e n t"],
["kuus", "k u u s"],
["mind", "m i n t"],
["minutit", "m i n u tt i tt"],
["neli", "n e l i"],
["null", "n u l l"],
["palun", "p a l u n"],
["sada", "s a t a"],
["seitse", "s e i t s e"],
["teist", "t e i s t"],
["tundi", "t u n t i"],
["üheksa", "ue h e k s a"],
["üheksa(2)", "ue e k s a"],
["üheksa(3)", "oe e k s a"],
["üks", "ue k s"],
["viis", "v i i s"],
];
