var wordList = [
["alarm", "AH L AA R M"],
["and", "AH N D"],
["and(1)", "AE N D"],
["at", "AE T"],
["clock", "K L AA K"],
["eight", "EY T"],
["eighteen", "EY T IY N"],
["eighty", "EY T IY"],
["eleven", "IH L EH V AH N"],
["eleven(1)", "IY L EH V AH N"],
["fifteen", "F IH F T IY N"],
["fifty", "F IH F T IY"],
["five", "F AY V"],
["for", "F AO R"],
["for(1)", "F ER"],
["for(2)", "F R ER"],
["forty", "F AO R T IY"],
["four", "F AO R"],
["fourteen", "F AO R T IY N"],
["from", "F R AH M"],
["from(1)", "F ER M"],
["hours", "AW ER Z"],
["hours(1)", "AW R Z"],
["hundred", "HH AH N D R AH D"],
["hundred(1)", "HH AH N D R IH D"],
["hundred(2)", "HH AH N ER D"],
["hundred(3)", "HH AH N D ER D"],
["in", "IH N"],
["me", "M IY"],
["minutes", "M IH N AH T S"],
["nine", "N AY N"],
["nineteen", "N AY N T IY N"],
["ninety", "N AY N T IY"],
["now", "N AW"],
["oh", "OW"],
["one", "W AH N"],
["one(1)", "HH W AH N"],
["please", "P L IY Z"],
["set", "S EH T"],
["seven", "S EH V AH N"],
["seventeen", "S EH V AH N T IY N"],
["seventy", "S EH V AH N T IY"],
["seventy(1)", "S EH V AH N IY"],
["six", "S IH K S"],
["sixteen", "S IH K S T IY N"],
["sixty", "S IH K S T IY"],
["ten", "T EH N"],
["the", "DH AH"],
["the(1)", "DH IY"],
["thirteen", "TH ER T IY N"],
["thirty", "TH ER D IY"],
["thirty(1)", "TH ER T IY"],
["three", "TH R IY"],
["timer", "T AY M ER"],
["to", "T UW"],
["to(1)", "T IH"],
["to(2)", "T AH"],
["twelve", "T W EH L V"],
["twenty", "T W EH N T IY"],
["twenty(1)", "T W EH N IY"],
["two", "T UW"],
["up", "AH P"],
["wake", "W EY K"],
];
